export const CURRENCY_KEY = 'currency'
export const IS_GREY_KEY = 'is_grey'
export const REINFORCEMENT_PURCHASES_KEY = 'reinforcement_purchases'
export const MAX_LIVES_KEY = 'max_lives'
export const PETS_OWNED_STATE_KEY = 'pet_state'
export const ACTIVE_PET_KEY = 'active_pet'